name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "1c5acb30-c115-4339-8bb8-0ea301baf19f"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "fbf701feb96f4573b5160116cf0c3fd7"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
