name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "06ea6714-1177-4b47-90f1-6303494579d9"
database_name = "notes-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "  fee440f8d5e148b8bb4412d566427838"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
